### ISSUE TITLE
"No such file or directory: './result/result.txt'" when training Macro placement

### ISSUE THREAD

**Issue by ybj-catherine** [Thinklab-SJTU/EDA-AI#1]
when I try to execute the code of Macro Placement section in Training part, I get an error:

File "/home/xxx/EDA-AI/place_env.py", line 103, in __init__
    self.f = open("./result/result.txt", 'w')
FileNotFoundError: [Errno 2] No such file or directory: './result/result.txt'

It seems that it is due to the lack of result.txt file in the directory"/home/xxx/EDA-AI/", could you please tell me where can I find this file?

**Comment by PKUTAN** [comment]
Have you found the file?

**Comment by Rogerity** [comment]
> Have you found the file?

You can create a new folder named "result" or just change the path
