### ISSUE TITLE
Cannot run the training commands in the Readme.md 

### ISSUE THREAD

**Issue by tianpeiyang** [Thinklab-SJTU/EDA-AI#15]
I have a problem running all these commands. 
Specifically, by running the 'Place' task
```
python main.py --task "place" --algo ppo --use-gae --lr 2.5e-4 --clip-param 0.1 --value-loss-coef 0.5 --num-processes 1 --num-steps 2840 --num-mini-batch 4 --log-interval 1 --use-linear-lr-decay --entropy-coef 0.01
```
Firstly, it has the error : FileNotFoundError: [Errno 2] No such file or directory './result/result.txt' 
I manually mkdir ./result and then the error is as follows:
![image](https://user-images.githubusercontent.com/4443373/190332222-0046af3e-518e-41db-b337-24adf629fbf4.png)
I tried running the 'Joint Macro/Standard cell Placement' task:
```
python EDA-AI/main.py --task "fullplace" --algo ppo --use-gae --lr 2.5e-4 --clip-param 0.1 --value-loss-coef 0.5 --num-processes 1 --num-steps 2840 --num-mini-batch 4 --log-interval 1 --use-linear-lr-decay --entropy-coef 0.01
```
It also has the error : FileNotFoundError: [Errno 2] No such file or directory './DeepPlace/result/result.txt' 
I manually mkdir ./DeepPlace/result 
Then it said: FileNotFoundError: [Errno 2] No such file or directory './DeepPlace/data/n_edges_710.dat'
![image](https://user-images.githubusercontent.com/4443373/190332747-7231c56f-3562-4c11-95d5-63e5ce524650.png)
This cannot be fixed by manually mkdir ./DeepPlace/data, there is no  n_edges_710.dat in this directory.

**Comment by Rogerity** [comment]
It seems that you first need to update your code and then create a new folder named "result" under EDA/AI.

1. There is a solution for your first question in the previous Issus: https://github.com/Thinklab-SJTU/EDA-AI/issues/10#issuecomment-1128276403. Hope that will be helpful.
2. There is no need to create ./DeepPlace/result. Just try
```
cd ..
python EDA-AI/main.py --task "fullplace" --algo ppo --use-gae --lr 2.5e-4 --clip-param 0.1 --value-loss-coef 0.5 --num-processes 1 --num-steps 2840 --num-mini-batch 4 --log-interval 1 --use-linear-lr-decay --entropy-coef 0.01
```

**Comment by tianpeiyang** [comment]
I found the solution to the first problem in https://github.com/Thinklab-SJTU/EDA-AI/issues/10 and it works!
The second one is about the fullplace_env.py, some paths are fixed and should be corrected.
Also, you may need to change PlaceObj.py in Line 577, pass a value not the tensor to fill_()
