### ISSUE TITLE
grid size in the code and in the firure 6 of thesis

### ISSUE THREAD

**Issue by ybj-catherine** [Thinklab-SJTU/EDA-AI#16]
When running the macro placement, the grid size in the code is set as 32.
And figure 6 shows in thesis shows visualization of macro (in orange) /standard cell (in blue) placement  on  circuits adaptec3 (shown as followed). While in this figure the grid size is set as 25000.
So how do you generate this 25000 size visualization from 32 size of grid placement
![image](https://user-images.githubusercontent.com/90683795/191669856-9c8d47fd-4a03-4172-b9be-30938569235f.png)

**Comment by Rogerity** [comment]
After all macros were placed,  we adopted gradient-based optimization placer to obtain complete placement solution. This figure then shows the visualization of all cells, so here the size is equal to the original board size (namely 25000).
