### ISSUE TITLE
version incompatible

### ISSUE THREAD

**Issue by yangbo19** [Thinklab-SJTU/EDA-AI#17]
I met the version incompatible  about gym when use the command "pip install -r requirements.txt".
In the requirment.txt , when install "stable-baselines3",  it requires gym>=0.17, but the latest version of baselines  requires gym <0.16
![image](https://user-images.githubusercontent.com/95022180/198996550-66787441-192f-4dad-9062-0c6f83a5d42d.png)
 Could you tell me how to address this issue.

**Comment by Rogerity** [comment]
I think the version requirement in baselines does not need to be strictly satisfied.
