### ISSUE TITLE
obs_space's dimension

### ISSUE THREAD

**Issue by ybj-catherine** [Thinklab-SJTU/EDA-AI#18]
hi, obs_space is defined in place_env.py:
![image](https://user-images.githubusercontent.com/90683795/200786589-fc93807d-1ac9-48af-ac0a-30036de01dc2.png)
I'm confused that why the dimension of obs_space is set as (1,84,84).
Thanks!

**Comment by WAYKEN-TSE** [comment]
> 

hi，i also have this question,have u known why now?

**Comment by liqianxi** [comment]
My guess is that before applying the CNN layers, they need to upsample the board state from 32*32 to 84*84 to make it larger so that more conv layers can be applied.

**Comment by Rogerity** [comment]
> My guess is that before applying the CNN layers, they need to upsample the board state from 32_32 to 84_84 to make it larger so that more conv layers can be applied.

That's right.
