### ISSUE TITLE
The boost version

### ISSUE THREAD

**Issue by PKUTAN** [Thinklab-SJTU/EDA-AI#2]
Of which version of boost did you install?

**Comment by Rogerity** [comment]
You can use apt-get command: `sudo apt-get install libboost-all-dev`

**Comment by tztgogo** [comment]
![image](https://user-images.githubusercontent.com/54180691/159394025-93f08943-503f-42f6-8e0d-8e142acb6371.png)
when I run make the error arises.
my boost version is 1.76

**Comment by Rogerity** [comment]
I am unfamiliar with this problem. Maybe you could ask the author of DREAMPlace for help.

**Comment by PKUTAN** [comment]
THX，and where is the folder:DeepPlace

**Comment by PKUTAN** [comment]
Is the repositery DREAMPlace and baseline download under the EDA-AI root directory?

**Comment by Rogerity** [comment]
Both are okay.
