### ISSUE TITLE
I had a problem when i run the training code, just said "indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by CliY520** [Thinklab-SJTU/EDA-AI#21]
All wrong like:

/home/graph/anaconda3/lib/python3.8/site-packages/dgl/heterograph.py:72: DGLWarning: Recommend creating graphs by 
 `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning('Recommend creating graphs by `dgl.graph(data)`'
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    main()
  File "main.py", line 133, in main
    obs, done, reward = envs.step(action)
  File "/home/cjq/EDA/EDA-AI/DeepPlace/place_env.py", line 125, in step
    x, y = search(self.obs[0, 0], x, y, 0, self.n)
  File "/home/cjq/EDA/EDA-AI/DeepPlace/place_env.py", line 42, in search
    if ob[x, y] < 1.0:
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by liqianxi** [comment]
Likely the tensor ob, x or y are on different devices (say some of them are on GPU), try to load these tensors on the same device and you can print these tensors to check the device info.

**Comment by CliY520** [comment]
>yes， I find it is like what you said. x and y on the GPU, but obs on the CPU. And if I use 'envs.obs.to('cuda:0'), it didn't work, which obs was on CPU. I am not good at tensor or pytorch

**Comment by CliY520** [comment]
我发现DreamPlace要求的pytorch版本和baseline要求的pytorch版本不一致，baseline需要大于1.11，但是DreamPlace说其只在1.6-1.8上成功过。我下的1.13的pytorch又会导致问题

**Comment by CliY520** [comment]
我已经解决了，修改代码
1.对place_env.py文件中的Placement类添加to函数，
def to(self, device):
        self.obs = self.obs.to(device)
2.在main函数中第103行(obs = envs.reset())后面添加代码:
envs.to(device)
就可以解决obs在cpu而不能放在gpu上的问题了

**Comment by Rogerity** [comment]
Thanks for your comments. I believe that your solution would be helpful to those facing the same problem. As for the version of pytorch, I think the requirements for DREAMPlace is more important.
