### ISSUE TITLE
problem on drawing the picture of circuit adaptec3

### ISSUE THREAD

**Issue by WAYKEN-TSE** [Thinklab-SJTU/EDA-AI#23]
i use the way of gnuplot to draw the circuit, but i don't know how to draw the macro,since each macro will occupy a different area size
<img width="906" alt="adaptec gp pl" src="https://user-images.githubusercontent.com/103988869/224892426-9fd01bfb-7c91-41a8-9f94-5b7120f084d1.png">

**Comment by AOrigin** [comment]
您好，请问你解决了吗？可以留下您的邮箱联系您吗

**Comment by Rogerity** [comment]
I think matplotlib.patches.Rectangle may help if you are using matplotlib.
