### ISSUE TITLE
Getting error when running placement algorithmn

### ISSUE THREAD

**Issue by PKUTAN** [Thinklab-SJTU/EDA-AI#3]
![image](https://user-images.githubusercontent.com/101382589/159870972-e54d5385-7a4a-408e-be26-8686f561d015.png)

I have env that has pytorch with cudatoolkit11.3,and dgl-cuda-11.3,I have no idea why it cannot find the cuda not detected

**Comment by Rogerity** [comment]
I think there may be something wrong with your CUDA and cuDNN environment.

**Comment by PKUTAN** [comment]
I set up my environment and everything seems to be right.However the errror arrives.
![image](https://user-images.githubusercontent.com/101382589/160230684-503f82b0-fa8c-4743-acba-82e1df8db08e.png)

**Comment by Rogerity** [comment]
The environment in this project is not the latest so it is not incompatible with yours? Actually I haven't met this bug before.

**Comment by ybj-catherine** [comment]
> I set up my environment and everything seems to be right.However the errror arrives. ![image](https://user-images.githubusercontent.com/101382589/160230684-503f82b0-fa8c-4743-acba-82e1df8db08e.png) Is there some tensor-numpy type bug in your code?

I got the same error like this
