### ISSUE TITLE
code publication

### ISSUE THREAD

**Issue by Pxx-X** [Thinklab-SJTU/EDA-AI#30]
hi, thank you for your brilliant work.
I can't find the code of paper "PreRoutGNN for Timing Prediction with Order Preserving Partition: Global Circuit Pre-training, Local Delay Learning and Attentional Cell Modeling", can you provide it?

**Comment by ECNUACRush** [comment]
https://arxiv.org/pdf/2403.00012v2

**Comment by zerzerzerz** [comment]
We have already make our code publicly available in `PreRoutGNN/README.md` Thank you for your interest in our work. We are looking forward to your feedback.
