### ISSUE TITLE
Training with isdp2005-2015 data

### ISSUE THREAD

**Issue by PKUTAN** [Thinklab-SJTU/EDA-AI#4]
Is there any API to the data? 
From the main.py there is only API to the example dataset

**Comment by Rogerity** [comment]
The ISPD2005 dataset can be obtained from https://github.com/limbo018/DREAMPlace/blob/master/benchmarks/ispd2005_2015.py.

**Comment by PKUTAN** [comment]
What a mean is that how to convert data in ispd to training data.
I only see the training for the n_edge_710

**Comment by PKUTAN** [comment]
How do you derive the movable macro dataset of adaptec3:n_edge_710.txt
and from the source code, it seems like that you generate a placement environment without considering the 13 fixed macro,and just place the 710 movable macro sequentially?

Thanks for answering my question!

**Comment by PKUTAN** [comment]
How do you derive the movable macro dataset of adaptec3:n_edge_710.txt
and from the source code, it seems like that you generate a placement environment without considering the 13 fixed macro,and just place the 710 movable macro sequentially?

Thanks for answering my question!

**Comment by Rogerity** [comment]
We filter out some macros in the original dataset by preprocessing, especially those smaller and isolated ones.
