### ISSUE TITLE
ModuleNotFoundError: No module named 'dreamplace.ops.rmst_wl.rmst_wl_cpp'

### ISSUE THREAD

**Issue by WOOSHIK-M** [Thinklab-SJTU/EDA-AI#9]
Hi, I'm trying to implement your algorithm.

I installed packages as your description, but the error occurred.
How does `rmst_wl_cpp` file be created?
I assume that `rmst_wl_cpp.py` has to be created and imported.
However, I cannot find the file even after implementing `make` and `make install`. 

Thanks.

**Comment by PKUTAN** [comment]
> Hi, I'm trying to implement your algorithm.
> 
> I installed packages as your description, but the error occurred. How does `rmst_wl_cpp` file be created? I assume that `rmst_wl_cpp.py` has to be created and imported. However, I cannot find the file even after implementing `make` and `make install`.
> 
> Thanks.
you need to make your environment as Dreamplace instructed

**Comment by WOOSHIK-M** [comment]
I run as below.

in `EDA-AI` dir,
```
$ mkdir build && cd build
$ cmake ..
$ make
``` 

However, I still could not find `dreamplace.ops.rmst_wl.rmst_wl_cpp`...
How can I handle this problem?

**Comment by PKUTAN** [comment]
> I run as below.
> 
> in `EDA-AI` dir,
> 
> ```
> $ mkdir build && cd build
> $ cmake ..
> $ make
> ```
> 
> However, I still could not find `dreamplace.ops.rmst_wl.rmst_wl_cpp`... How can I handle this problem?

When doing make.
You need to first modify the CMakeLists.txt in DREAMPlace/dreamplace/ops/CMakeLists.txt
add add_subdirectory(rmst_wl) to DREAMPlace/dreamplace/ops/CMakeLists.txt
Then you may run make to build your environment

**Comment by sungdongy** [comment]
@WOOSHIK-M 
Did you solve the problem?
I still have a problem that i cannot import the rmst_wl_cpp module even I modify the CMakeLists.txt

**Comment by CliY520** [comment]
you can see this https://github.com/limbo018/DREAMPlace/issues/66.  and in your dreamplace code such "dreamplace/ops/CMakeLists.txt" line 12 to open it
